import { StyleSheet } from "react-native";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";
import { colorConstant, fontConstant } from "../../utils/constant";

export default StyleSheet.create({
    maincontainer: {
      backgroundColor: 'black',
      flex: 1,
    },
    msgButtom: {
      height: 30,
      width: 30,
    },
    magzView: {
      width: responsiveScreenWidth(100),
      alignSelf: 'center',
      height: responsiveScreenHeight(30),
      marginVertical: 5,
    },
    magzImage: {
      width: responsiveScreenWidth(95),
      height: responsiveScreenHeight(30),
      alignSelf: 'center',
      borderRadius: 12,
    },
    img: {
      width: responsiveScreenWidth(48),
      borderRadius: 12,
      aspectRatio: 1.5,
    },
    mapView: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      width: '100%',
      alignSelf: 'center',
      alignItems: 'center',
    },
    touchMapView: {
      width: responsiveScreenWidth(47.6),
      marginTop: responsiveScreenHeight(1.5),  
      borderRadius: 12,
      alignItems: 'center',
      alignSelf: 'center',
      marginHorizontal: responsiveScreenHeight(0.4),
    },
    maxLike: {
      borderRadius: 8,
      height: responsiveScreenHeight(25),
      width: responsiveScreenWidth(96),
    },
    maxLikeView: {
      width: responsiveScreenWidth(93),
      height: responsiveScreenHeight(26),
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: responsiveScreenHeight(2),
      overflow: 'hidden',
      elevation: 4,
      shadowOffset: {width: 0, height: 2}, 
      shadowOpacity: 0.9, 
      shadowRadius: 4,
      borderRadius: 8,
      alignSelf: 'center',
    },
    mainText: {
      color: colorConstant.white,
      fontSize: 18,
      fontFamily: fontConstant.bold,
    },
    textView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: responsiveScreenWidth(8),
      alignItems: 'center',
      marginTop: 10,
    },
    logocontainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 65,
      paddingHorizontal: responsiveScreenWidth(4),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colorConstant.black,
    },
    cardcontainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignSelf: 'center',
      width: responsiveScreenWidth(95),
      marginTop: responsiveScreenHeight(8),
    },
    mainimagecontainer: {
      justifyContent: 'center',
    },
    imagebackground: {
      width: responsiveScreenWidth(45),
      justifyContent: 'center',
      alignItems: 'center',
      height: responsiveScreenHeight(15),
    },
    otherImg: {
      width: responsiveScreenWidth(45),
      height: responsiveScreenHeight(23),
      alignSelf: 'center',
    },
    longImg: {
      width: responsiveScreenWidth(50),
      height: responsiveScreenHeight(46),
    },
    rowContainer: {
      width: '100%',
      flexDirection: 'row',
      alignSelf: 'center',
    },
    logo: {
      resizeMode: 'contain',
      height: 70,
      width: 70,
    },
    postImg: {
      resizeMode: 'cover',
      height: responsiveScreenHeight(29.2),
      width: responsiveScreenWidth(43),
      marginTop: responsiveScreenWidth(1),
      alignSelf: 'center',
      borderRadius: 8,
    },
    mainView: {
      alignSelf: 'center',
      justifyContent: 'center',
      width: responsiveScreenWidth(50),
      padding: 8,
    },
    notFoundView: {
      justifyContent: 'center',
      height: responsiveScreenHeight(20),
      alignSelf: 'center',
    },
    notFoundText: {
      color: colorConstant.white,
      alignSelf: 'center',
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
    },
    listStyle:{marginBottom: responsiveScreenHeight(3)},
    allText:{paddingHorizontal: responsiveScreenWidth(4)},
    showAll:{color: colorConstant.lightWhite, fontSize: 13},
    letestTopic:{color: colorConstant.white, fontSize: 16},
    placeholderContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 10,
      justifyContent: 'center',
    },
    placeholderImage: {
      width: responsiveScreenWidth(47),
      height: responsiveScreenHeight(30),
      borderRadius: 12,
      backgroundColor: '#E1E9EE', 
      marginRight: 10,
    },
    placeholderText: {
      flex: 1,
      height: responsiveScreenHeight(30),
      borderRadius: 12,
      backgroundColor: '#E1E9EE', 
    },
    placeholderImageMain: {
      width: responsiveScreenWidth(95),
      height: responsiveScreenHeight(28),
      borderRadius: 12,
      backgroundColor: '#E1E9EE', 
      alignSelf: 'center',
    },
    placeholderContainerNew: {
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: responsiveScreenHeight(1),
    },
  });
  