import {imageConstant} from './constant';

export const categoryList = [
  {
    key: 'neroPic',
    image: imageConstant.neropic,
    name: 'NERO PIC',
    type: 'Photography',
    label: 'Photography',
    format: 'PNG,JPEG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: 'PIC',
    value: 'PIC',
  },
  {
    key: 'neroArt',
    image: imageConstant.neroart,
    name: 'NERO ART',
    type: 'Digital Art',
    label: 'Digital Art',
    format: 'PNG,JPEG,SVG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: 'ART',
    value: 'ART',
  },
  {
    key: 'neroTxt',
    image: imageConstant.nerotxt,
    name: 'NERO TXT',
    type: 'Typography',
    label: 'Typography',
    format: 'PNG,JPEG,SVG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: 'TXT',
    value: 'TXT',
  },
  {
    key: 'neroMov',
    image: imageConstant.neromov,
    name: 'NERO MOV',
    type: 'Motion Graphics',
    label: 'Motion Graphics',
    format: 'MP4,GIF',
    minDimesion: '16:9,4:3',
    minResolution: '300 Dpi or above',
    tagType: 'MOV',
    value: 'MOV',
  },
  {
    key: 'nero3dx',
    image: imageConstant.nero3dx,
    name: 'NERO 3DX',
    type: '3D Art',
    label: '3D Art',
    format: 'PNG,JPEG,SVG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: '3DX',
    value: '3DX',
  },
  {
    key: 'neroVog',
    image: imageConstant.nerovog,
    name: 'NERO VOG',
    type: 'Fashion',
    label: 'Fashion',
    format: 'PNG,JPEG,SVG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: 'VOG',
    value: 'VOG',
  },
  {
    key: 'neroArc',
    image: imageConstant.neroarc,
    name: 'NERO ARC',
    type: 'Architecture',
    label: 'Architecture',
    format: 'PNG,JPEG,SVG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: 'ARC',
    value: 'ARC',
  },
  {
    key: 'neroPrd',
    image: imageConstant.neroprd,
    name: 'NERO PRD',
    type: 'Product Design',
    label: 'Product Design',
    format: 'PNG,JPEG,SVG',
    minDimesion: '3500px X 4500px',
    minResolution: '300 Dpi or above',
    tagType: 'PRD',
    value: 'PRD',
  },
  {
    key: 'neroMob',
    image: imageConstant.neromob,
    name: 'NERO MOB',
    type: 'Mobile Photography',
    label: 'Mobile Photography',
    format: 'PNG,JPEG',
    minDimesion: '2000px X 2000px',
    minResolution: '18MPixels',
    tagType: 'MOB',
    value: 'MOB',
  },
  {
    key: 'neroLif',
    image: imageConstant.nerolif,
    name: 'NERO LIF',
    type: 'Lifestyle',
    label: 'Lifestyle',
    format: 'PNG,JPEG',
    minDimesion: '2000px X 2000px',
    minResolution: '18MPixels',
    tagType: 'LIF',
    value: 'LIF',
  },
];
