import { StyleSheet } from "react-native";
import { colorConstant, fontConstant } from "../../utils/constant";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";

export default StyleSheet.create({
    mainContainer: {
      backgroundColor: colorConstant.black,
      flex: 1,
    },
    tagnameText:{color: 'white'},
    renderItemView:{
      padding: responsiveScreenWidth(1),
      backgroundColor: colorConstant.black,
      borderRadius: 8,
      paddingHorizontal: responsiveScreenWidth(3),
    },
    usernameTouch: {width: responsiveScreenWidth(80), padding: 8},
    usernameFlatlist: {
      borderWidth: 1,
      borderColor: colorConstant.bordercolor,
      width: responsiveScreenWidth(90),
      borderRadius: 8,
      alignSelf: 'center',
    },
    usernameText: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2),
    },
    unselected: {
      width: 20,
      height: 20,
      marginRight: 8,
    },
    selected: {
      width: 30,
      height: 30,
      marginRight: 5,
    },
    crosstouch: {
      justifyContent: 'center',
      height: 20,
      width: 20,
      alignSelf: 'flex-end',
      marginBottom: responsiveScreenHeight(2),
    },
  
    notApproveText: {
      color: colorConstant.white,
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
      textAlign: 'center',
      justifyContent: 'center',
    },
    modalView1: {
      backgroundColor: colorConstant.backgroundBlack,
      alignSelf: 'center',
      padding: responsiveScreenHeight(2.5),
      height: responsiveScreenHeight(20),
      width: responsiveScreenWidth(95),
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: 'gray',
    },
    postLiveView: {
      backgroundColor: colorConstant.black,
      width: responsiveScreenWidth(95),
      alignSelf: 'center',
      borderRadius: 12,
      // justifyContent: 'center',
      // paddingVertical: responsiveScreenHeight(10),
      borderWidth: 0.5,
      borderColor: 'white',
      flex: 0.7,
    },
    lastImg: {
      width: responsiveScreenWidth(90),
      height: responsiveScreenHeight(70),
      alignSelf: 'center',
      borderRadius: 4,
    },
    cross: {
      width: 20,
      height: 20,
      alignSelf: 'flex-end',
      marginVertical: 10,
      marginRight: 5,
    },
    modalView: {
      backgroundColor: colorConstant.backgroundBlack,
      borderRadius: 8,
      alignSelf: 'center',
      justifyContent: 'center',
      width: responsiveScreenWidth(95),
      height: responsiveScreenHeight(80),
    },
    closeImg: {width: 20, height: 20, marginLeft: -5, marginTop: -5},
    termText: {
      paddingVertical: responsiveScreenHeight(2),
      flexDirection: 'row',
      alignSelf: 'center',
      width: responsiveScreenWidth(80),
      justifyContent: 'center',
    },
    text3: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(1.9),
      alignSelf: 'center',
      textAlign: 'center',
    },
    desText: {
      color: colorConstant.gray,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(1.9),
      width: responsiveScreenWidth(85),
      textAlign: 'center',
      alignSelf: 'center',
      paddingVertical: responsiveScreenHeight(3),
      marginTop: responsiveScreenHeight(3),
    },
    firstText: {
      color: colorConstant.white,
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(3),
      textAlign: 'center',
    },
    postLiveTouch: {
      alignSelf: 'flex-end',
      marginVertical: responsiveScreenHeight(2.5),
      marginRight: responsiveScreenWidth(3),
    },
    postLiveModal: {
      backgroundColor: colorConstant.black,
      width: responsiveScreenWidth(95),
      alignSelf: 'center',
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: 'white',
      flex: 0.7,
    },
    suggestView: {
      flexDirection: 'row',
      gap: responsiveScreenWidth(2),
      marginVertical: responsiveScreenWidth(2),
      width: responsiveScreenWidth(80),
      marginLeft: responsiveScreenWidth(20),
      paddingHorizontal: 5,
      flexWrap: 'wrap',
    },
    removeImg: {
      width: 28,
      height: 28,
      alignSelf: 'center',
      marginLeft: responsiveScreenWidth(-2),
      marginTop: responsiveScreenHeight(-2),
    },
    removeTouch: {
      width: 28,
      height: 28,
      marginBottom: responsiveScreenHeight(15),
      justifyContent: 'center',
    },
    touch: {
      width: responsiveScreenWidth(40),
      height: responsiveScreenHeight(10),
    },
    imageView: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      width: responsiveScreenWidth(95),
      justifyContent: 'center',
      marginVertical: responsiveScreenHeight(2),
    },
    selectedTagText: {
      color: colorConstant.black,
    },
    errorView: {
      marginTop: '1%',
      marginLeft: '1%',
      marginBottom: '-2%',
    },
    errorText: {
      color: 'red',
      fontSize: responsiveScreenFontSize(1.7),
      fontFamily: fontConstant.regular,
    },
    selectedTagContainer: {
      flexDirection: 'row',
      backgroundColor: '#dfdfdf',
      justifyContent: 'center',
      alignItems: 'çenter',
      borderRadius: 5,
      padding: 5,
    },
    centerContainer: {
      alignSelf: 'center',
      justifyContent: 'center',
      width: responsiveScreenWidth(80),
      marginBottom: responsiveScreenHeight(3),
    },
    publishImg: {
      resizeMode: 'cover',
      width: responsiveScreenWidth(45),
      height: responsiveScreenHeight(17),
      // marginVertical: responsiveScreenHeight(3),
      alignSelf: 'center',
    },
    centerText: {
      color: colorConstant.lightText,
      textAlign: 'center',
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2),
    },
  
    clickText: {
      color: colorConstant.white,
      textAlign: 'center',
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
    },
    rowTextContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
    },
    rowConatiner: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignSelf: 'center',
      width: responsiveScreenWidth(90),
      marginVertical: responsiveScreenHeight(1),
    },
    leftText: {
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2),
      fontFamily: fontConstant.bold,
    },
    input: {
      backgroundColor: colorConstant.backgroundBlack,
      width: responsiveScreenWidth(75),
      borderRadius: 12,
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2),
      paddingHorizontal: responsiveScreenWidth(4),
      height: responsiveScreenHeight(5.5),
      fontFamily: fontConstant.regular,
    },
    tagsInputView: {
      backgroundColor: colorConstant.backgroundBlack,
      width: responsiveScreenWidth(75),
      borderRadius: 12,
      height: responsiveScreenHeight(5.5),
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignSelf: 'center',
    },
    tagInput: {
      backgroundColor: colorConstant.black,
      borderRadius: 4,
      marginVertical: 5,
      marginHorizontal: 4,
      justifyContent: 'center',
    },
    chipText: {
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2),
      fontFamily: fontConstant.regular,
      alignSelf: 'center',
    },
    suggestText: {
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(1.8),
      fontFamily: fontConstant.medium,
    },
    itemText: {
      color: colorConstant.white,
      marginLeft: 10,
      borderWidth: 1,
      borderBottomColor: colorConstant.white,
    },
    con:{justifyContent: 'center', alignItems: 'center'},
    headText: {
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2.3),
      fontFamily: fontConstant.regular,
      alignSelf: 'center',
      marginVertical: responsiveScreenHeight(1),
    },
    multiInputs: {
      backgroundColor: colorConstant.backgroundBlack,
      width: responsiveScreenWidth(90),
      borderRadius: 12,
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2),
      height: responsiveScreenHeight(15),
      fontFamily: fontConstant.regular,
      alignSelf: 'center',
      textAlignVertical: 'top',
      paddingHorizontal: 10,
    },
    inputdes: {
      backgroundColor: colorConstant.backgroundBlack,
      width: responsiveScreenWidth(90),
      borderRadius: 12,
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2),
      height: responsiveScreenHeight(6),
      fontFamily: fontConstant.regular,
      alignSelf: 'center',
      textAlignVertical: 'top',
      paddingHorizontal: 10,
      marginBottom: responsiveScreenHeight(2),
    },
    publishButton: {
      resizeMode: 'contain',
      alignSelf: 'center',
      width: responsiveScreenWidth(45),
      height: responsiveScreenHeight(5),
      marginVertical: responsiveScreenHeight(5),
    },
    modalContainer: {
      backgroundColor: '#403735',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.36,
      shadowRadius: 6.68,
      elevation: 11,
      bottom: -10,
      position: 'absolute',
      height: responsiveScreenHeight(20),
      width: responsiveScreenWidth(100),
      borderRadius: 8,
      alignSelf: 'center',
    },
    mainModalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 22,
    },
    rowCon: {
      flexDirection: 'row',
      // alignItems:'center',
      alignSelf: 'center',
      justifyContent: 'space-between',
      width: responsiveScreenWidth(70),
      marginTop: responsiveScreenHeight(2),
    },
    profileText: {
      color: colorConstant.white,
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2.5),
      marginVertical: 5,
    },
    paginationLine: {
      width: 10,
      height: 2,
      backgroundColor: 'gray',
      marginHorizontal: 3,
  
      marginBottom: responsiveScreenHeight(-8),
    },
    activePaginationLine: {
      width: 20, // Make the active line slightly larger
      height: 2,
      backgroundColor: 'white',
      marginHorizontal: 3,
  
      marginBottom: responsiveScreenHeight(-8),
    },
    textcontainer: {marginTop: responsiveScreenHeight(3)},
    textcontainertext: {
      color: colorConstant.white,
      textAlign: 'center',
      fontFamily: fontConstant.light,
      fontSize: 16,
    },
    allicon: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      width: responsiveScreenWidth(100),
      alignSelf: 'center',
    },
    singleicon: {
      margin: 7,
      alignItems: 'center',
      width: responsiveScreenWidth(29),
      marginVertical: responsiveScreenHeight(2),
    },
    inactiveText: {
      color: '#979797',
      textAlign: 'center',
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(1.5),
      marginTop: responsiveScreenHeight(0.5),
      width: '100%',
    },
    activeText: {
      color: 'white',
      textAlign: 'center',
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(1.5),
      marginTop: responsiveScreenHeight(0.5),
      width: '100%',
    },
  
    modalContainer1: {
      width: responsiveScreenWidth(100),
      height: responsiveScreenHeight(74),
      alignSelf: 'center',
      bottom: responsiveScreenHeight(5),
      backgroundColor: colorConstant.backgroundBlack,
      borderRadius: 5,
  
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 2,
        height: 5,
      },
      shadowOpacity: 1,
      elevation: 11,
      marginTop: responsiveScreenHeight(20),
    },
    mainModalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 22,
      width: '90%',
    },
    modalrowContainer: {
      flexDirection: 'row',
      // alignItems:'center',
      alignSelf: 'center',
      justifyContent: 'space-between',
      width: responsiveScreenWidth(70),
      marginTop: responsiveScreenHeight(2),
    },
    hw2:{
      width: responsiveScreenHeight(2),
      height: responsiveScreenHeight(2),
    },
    modaltextinput: {
      backgroundColor: colorConstant.backgroundBlack,
      width: responsiveScreenWidth(60),
      height: responsiveScreenHeight(5.5),
      borderRadius: 15,
      color: colorConstant.white,
      paddingHorizontal: 9,
      borderWidth: 1,
      borderColor: colorConstant.bordercolor,
      marginLeft: responsiveScreenWidth(-0.5),
      flexDirection: 'row',
      alignItems: 'center',
      gap: responsiveScreenWidth(2),
      marginRight: responsiveScreenWidth(10),
    },
    whiteline: {
      alignSelf: 'center',
      marginBottom: responsiveScreenHeight(2),
      marginTop: responsiveScreenHeight(2),
    },
    modalinputcontainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      paddingHorizontal: responsiveScreenWidth(15),
      gap: responsiveScreenWidth(15),
      marginRight: responsiveScreenWidth(10),
    },
    modaltextinputstyle: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(1.8),
      width: responsiveScreenWidth(45),
    },
    modaltagscontainer: {
      justifyContent: 'center',
      alignItems: 'center',
      height: responsiveScreenHeight(35),
    },
    modaltagstext: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2),
      alignSelf: 'center',
      textAlign: 'center',
    },
    text123:{color: 'white', fontSize: 18},
    modalsingletags: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: responsiveScreenHeight(3),
      paddingHorizontal: responsiveScreenWidth(5),
    },
    view12:{
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: responsiveScreenWidth(90),
      paddingLeft: responsiveScreenWidth(3),
    },
    view13:{
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    searchtagText:{
      color: colorConstant.placeholdercolor,
      fontSize: responsiveScreenFontSize(2),
    },
    textinputnew: {
      backgroundColor: colorConstant.backgroundBlack,
      marginTop: responsiveScreenHeight(1),
      width: responsiveScreenWidth(90),
      height: responsiveScreenHeight(5.5),
      borderRadius: 5,
      color: colorConstant.white,
      paddingHorizontal: 9,
      borderWidth: 1,
      borderColor: colorConstant.bordercolor,
      // marginLeft: responsiveScreenWidth(-0.5),
  
      justifyContent: 'space-around',
      flexDirection: 'row',
      alignItems: 'center',
      // paddingHorizontal:responsiveScreenWidth(2)
    },
  });