import { Dimensions, StyleSheet } from "react-native";
import { responsiveScreenFontSize, responsiveScreenHeight, responsiveScreenWidth } from "react-native-responsive-dimensions";
import { colorConstant, fontConstant } from "../../utils/constant";
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
    maincontainer: {
      backgroundColor: 'black',
      flex: 1,
    },
    mb20:{marginBottom: responsiveScreenHeight(4)},
    selectImg:{
      resizeMode: 'contain',
      width: responsiveScreenWidth(5),
      height: responsiveScreenHeight(2),
    },
    selectText: {
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
    },
    radioTouch: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      width: responsiveScreenWidth(87),
      marginVertical: responsiveScreenHeight(0.8),
    },
    radiobg: {width: 20, height: 20, justifyContent: 'center'},
    radioImg: {width: 12, height: 12, alignSelf: 'center'},
    radioelse: {width: 20, height: 20},
    label: {
      color: colorConstant.white,
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
    },
    text1: {
      color: 'white',
      marginTop: responsiveScreenHeight(1),
      fontSize: responsiveScreenFontSize(2.2),
      fontFamily: fontConstant.regular,
      color: '#979797',
      textAlign: 'center',
    },
    deleteText1: {
      color: 'white',
      fontSize: responsiveScreenFontSize(2.5),
      fontFamily: fontConstant.bold,
      marginTop: responsiveScreenHeight(1),
    },
    crossTouch: {position: 'absolute', right: 7, top: 15},
    deleteTouch: {justifyContent: 'center', alignItems: 'center', gap: 7},
  
    commentMainContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: responsiveScreenWidth(93),
      paddingRight: responsiveScreenWidth(1.5),
      marginTop: responsiveScreenHeight(1),
    },
    cmtTextContainer: {
      color: colorConstant.white,
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
      alignSelf: 'flex-start',
      padding: 10,
    },
    arrowImg: {
      height: responsiveScreenHeight(3),
      width: responsiveScreenWidth(5),
    },
    hideView: {
      alignSelf: 'center',
      width: responsiveScreenWidth(95),
      justifyContent: 'center',
      flex: 1,
    },
    hideViewText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(2.5),
      alignSelf: 'center',
    },
    hideViewSubText: {
      color: 'white',
      fontSize: responsiveScreenFontSize(2),
      fontFamily: fontConstant.regular,
      alignSelf: 'center',
      textAlign: 'center',
    },
    crossImg: {position: 'absolute', right: 0, bottom: 100},
    mainView: {
      height: windowHeight,
      width: windowWidth,
      backgroundColor: 'black',
      transform: [{scaleY: 1}],
    },
    tagsContainer: {
      backgroundColor: '#2C2C2C',
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 15,
      marginTop: responsiveScreenHeight(1),
    },
    nameText: {
      fontFamily: fontConstant.regular,
      color: colorConstant.white,
      fontSize: responsiveScreenFontSize(2),
    },
    errorView: {
      marginTop: '1%',
      marginLeft: '1%',
      marginBottom: '-2%',
    },
    errorText: {
      color: 'red',
      fontSize: responsiveScreenFontSize(1.7),
      fontFamily: fontConstant.regular,
    },
    hideModalMainStyle: {
      position: 'absolute',
      bottom: responsiveScreenHeight(-7),
      alignSelf: 'center',
    },
    reportSelectTabText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(2.3),
      marginVertical: responsiveScreenWidth(2),
      marginBottom: responsiveScreenHeight(2),
    },
    sideModalContainer: {
      width: responsiveScreenWidth(100),
      height: responsiveScreenHeight(30),
      alignSelf: 'center',
      backgroundColor: colorConstant.black,
      borderRadius: 8,
      alignItems: 'center',
      borderColor: colorConstant.bordercolor,
      borderWidth: 1,
      paddingTop: responsiveScreenHeight(1),
    },
    reportmainText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(2.3),
      marginVertical: responsiveScreenWidth(2),
      marginBottom: responsiveScreenHeight(2),
    },
    reportModleMainText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(2.3),
      width: '90%',
      marginVertical: responsiveScreenWidth(2),
      marginBottom: responsiveScreenHeight(2),
    },
    hideModalMainText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(2.3),
      width: '90%',
      marginVertical: responsiveScreenWidth(2),
    },
    sideModalMainStyle: {
      position: 'absolute',
      bottom: responsiveScreenHeight(-7),
      alignSelf: 'center',
    },
    swiperContainer: {
      height: responsiveScreenHeight(40),
    },
    text: {
      color: colorConstant.gray,
      fontFamily: fontConstant.light,
      fontSize: 14,
    },
    btn: {
      backgroundColor: '#C2C1C1',
      width: 80,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
      height: 31,
    },
    headerTextView: {
      marginBottom: responsiveScreenHeight(1.5),
      justifyContent: 'center',
      alignItems: 'flex-start',
      // backgroundColor:'red',
      width: responsiveScreenWidth(95),
      // alignSelf:'center',
      marginTop: responsiveScreenWidth(3),
      marginLeft: responsiveScreenWidth(3),
    },
    subTextView: {
      marginBottom: responsiveScreenHeight(1.5),
      marginHorizontal: responsiveScreenWidth(3),
      justifyContent: 'center',
      // alignItems: 'center',
    },
    subText: {
      color: colorConstant.white,
      fontFamily: fontConstant.light,
      fontSize: 14,
    },
    headerText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: 17,
    },
    header: {
      marginBottom: responsiveScreenHeight(0.5),
      height: 60,
    },
    mainImg: {
      marginTop: responsiveScreenHeight(2),
    },
    profiledetails: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: responsiveScreenWidth(2.5),
      // marginTop: responsiveScreenHeight(1),
    },
    mainimage: {
      // justifyContent: 'center',
      // alignSelf: 'center',
      marginTop: responsiveScreenHeight(2),
      elevation: 4, // Android elevation for shadow
      shadowColor: 'lightgrey', // Shadow color
      shadowOffset: {width: 0, height: 2}, // Shadow offset
      shadowOpacity: 0.9, // Shadow opacity
      shadowRadius: 12, // Shadow radius
      borderRadius: 12,
      height: responsiveScreenHeight(40),
      alignSelf: 'center',
    },
    rowView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignSelf: 'center',
      alignItems: 'center',
      width: responsiveScreenWidth(94.5),
      position: 'absolute',
      bottom: 1,
      paddingVertical: responsiveScreenHeight(2),
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      borderBottomLeftRadius: 12,
      borderBottomRightRadius: 12,
      // opacity: 0.8,
    },
    underRowView: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignSelf: 'auto',
      alignItems: 'center',
      width: responsiveScreenWidth(32),
    },
    bottomImg: {
      resizeMode: 'contain',
      alignSelf: 'center',
      width: responsiveScreenWidth(7),
      height: responsiveScreenHeight(3),
    },
    sidemodaltext: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2.3),
    },
    reportMainView: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: responsiveScreenWidth(4),
      marginHorizontal: responsiveScreenWidth(5),
      marginVertical: responsiveScreenHeight(1),
      width: responsiveScreenWidth(90),
    },
    reportText: {
      color: 'red',
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2.3),
    },
    deleteMainView: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: responsiveScreenWidth(5),
      marginHorizontal: responsiveScreenWidth(5),
      marginVertical: responsiveScreenHeight(1),
      width: responsiveScreenWidth(90),
    },
    deleteImg: {
      width: 24,
      height: 24,
      resizeMode: 'contain',
    },
    deleteText: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2.3),
    },
    reportImage: {width: 27, height: 27},
    sidemodalimageView: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: responsiveScreenWidth(5),
      marginHorizontal: responsiveScreenWidth(5),
      marginVertical: responsiveScreenHeight(1),
      width: responsiveScreenWidth(90),
    },
    unfollowText: {
      fontSize: responsiveScreenFontSize(2),
      fontFamily: 'Sulphur Point',
      color: colorConstant.black,
      fontWeight: '600',
    },
    commentItem: {
      flexDirection: 'row',
      marginTop: responsiveScreenHeight(4),
      gap: responsiveScreenWidth(3),
      // height: responsiveScreenHeight(8),
      justifyContent: 'space-between',
      alignSelf: 'center',
      width: responsiveScreenWidth(89),
    },
    profilepic: {
      // backgroundColor: 'green',
      width: 25,
      height: 25,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    commenterName: {
      fontSize: 16,
      fontFamily: fontConstant.bold,
      color: colorConstant.white,
      marginBottom: responsiveScreenHeight(0.5),
    },
    commentText: {
      fontFamily: fontConstant.medium,
      color: colorConstant.white,
      marginBottom: responsiveScreenHeight(0.5),
    },
    commentTextContainer: {
      width: responsiveScreenWidth(65),
      paddingBottom: responsiveScreenHeight(2),
    },
    commenterProfileImage: {
      resizeMode: 'contain',
      width: 26,
      height: 26,
      borderRadius: 12.5,
    },
    modalContainer: {
      position: 'absolute',
      width: responsiveScreenWidth(95),
      height: responsiveScreenHeight(46),
      alignSelf: 'center',
      bottom: responsiveScreenHeight(5),
      backgroundColor: colorConstant.black,
      borderRadius: 5,
  
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 2,
        height: 5,
      },
      shadowOpacity: 1,
      elevation: 11,
    },
    textinputView: {
      alignSelf: 'center',
      backgroundColor: '#272727',
      width: responsiveScreenWidth(100),
      height: responsiveScreenHeight(8),
      position: 'absolute',
      bottom: responsiveScreenHeight(-7),
      justifyContent: 'center',
    },
    mr10:{marginRight: responsiveScreenWidth(1)},
    textinputcontainer: {
      backgroundColor: '#5A5A5A',
      width: responsiveScreenWidth(90),
      height: responsiveScreenHeight(5),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      // paddingHorizontal: responsiveScreenWidth(2),
      borderRadius: 20,
      // bottom: -30,
      position: 'absolute',
      alignSelf: 'center',
      borderWidth: 1,
      borderColor: colorConstant.bordercolor,
    },
    input: {
      width: responsiveScreenWidth(78),
      color: 'white',
      paddingHorizontal: responsiveScreenWidth(2),
    },
    listcontainer: {
      height: responsiveScreenHeight(45),
    },
    notFoundView: {
      justifyContent: 'center',
      height: responsiveScreenHeight(45),
      alignSelf: 'center',
    },
    notFoundText: {
      color: colorConstant.white,
      alignSelf: 'center',
      fontFamily: fontConstant.medium,
      fontSize: responsiveScreenFontSize(2),
    },
    bottomRowView: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      // justifyContent:'space-between',
      width: responsiveScreenWidth(93),
      marginVertical: responsiveScreenHeight(1),
    },
    bottomProfile: {
      resizeMode: 'contain',
      width: responsiveScreenWidth(6.8),
      height: responsiveScreenHeight(3),
      borderRadius: responsiveScreenWidth(3.5),
    },
    commentTextView: {
      marginLeft: responsiveScreenWidth(2.5),
      marginTop: responsiveScreenWidth(2),
    },
    dateText: {
      color: colorConstant.lightText,
      marginLeft: responsiveScreenWidth(2.5),
      marginBottom: responsiveScreenHeight(2),
      fontSize: responsiveScreenFontSize(1.8),
      fontFamily: fontConstant.regular,
    },
    titleText: {
      color: colorConstant.white,
      width: responsiveScreenWidth(95),
      alignSelf: 'center',
      marginTop: responsiveScreenWidth(2),
      fontSize: responsiveScreenFontSize(1.8),
      fontFamily: fontConstant.regular,
    },
    boldText: {
      color: colorConstant.white,
      fontFamily: fontConstant.bold,
      fontSize: responsiveScreenFontSize(2),
    },
    regularText: {
      color: colorConstant.white,
      fontFamily: fontConstant.regular,
      fontSize: responsiveScreenFontSize(2),
    },
    modalContent: {
      backgroundColor: 'black',
      height: responsiveScreenHeight(20),
      width: responsiveScreenWidth(85),
      borderRadius: responsiveScreenWidth(5),
  
      alignItems: 'center',
      paddingHorizontal: responsiveScreenWidth(3),
    },
    modalContainerdelete: {
      justifyContent: 'center',
      alignItems: 'center',
    },
  });